###################### Cephbeat Configuration Example #######################

# This file is an example configuration file highlighting only the most common
# options. The metricbeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#==========================  Modules configuration ============================
cephbeat.modules:

#------------------------------- cluster Module ------------------------------
  - module: cluster
    metricsets: ["cluster", "pools"]
    enabled: true
    period: 1s
    hosts: ["localhost"]
    cluster_conf_path: "/etc/ceph/main.conf"

output.elasticsearch:
  hosts: ["localhost:9200"]

#================================ Logging =====================================

# Sets log level. The default log level is error.
# Available log levels are: critical, error, warning, info, debug
logging.level: info

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

logging.to_files: true
logging.to_syslog: false
logging.files:
  path: logs
  name: cephbeat.log
  keepfiles: 7
